name: CI lint and test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.21.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, prettier, typescript]

      - name: Install dependencies
        run: pnpm ci

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Buid
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        run: pnpm build
